### ISSUE TITLE
React.js - How to import the USS API

### ISSUE THREAD

**Issue by foxprogs** [CristianDavideConte/universalSmoothScroll#1]
How can I use this library in react application?
I tried to do so
`import { uss } from 'universalsmoothscroll';`
so
`import uss from 'universalsmoothscroll';`
but nothing comes out.

**Comment by CristianDavideConte** [comment]
Hi, 
the way you're trying to import the library won't work with this API because it's not a module.
Every React application should have an `index.html` file that you can use to import all the API's `<script>`.
For more informations have a look at the [`Installation`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/Installation.md) section of the Readme.<br/>

**Quick Tip** 
All the API methods requires the `container` parameter to be an `HTMLElement` or the `window` element while in React you usually work with `ReactElements`. 
You can use [`Refs`](https://en.reactjs.org/docs/refs-and-the-dom.html) or [`React.findDOMNode`](https://en.reactjs.org/docs/react-dom.html#finddomnode) to perform the needed conversions.

If this solved your problem, I'm going to close this issue.

**Comment by foxprogs** [comment]
@CristianDavideConte OK, thanks. I will try.
