### ISSUE TITLE
How to use setYStepLengthCalculator with hrefSetup?

### ISSUE THREAD

**Issue by danfmn** [CristianDavideConte/universalSmoothScroll#10]
Hello,

Most methods currently require a reference to a container to be called.
In my case I'm using the `hrefSetup` and not referencing any specific containers. Without a container reference, how can I appropriately utilize `setYStepLengthCalculator` or something similar so that it works with the `hrefSetup` method?

Thank you!

**Comment by CristianDavideConte** [comment]
Hi, 
the [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) method automatically binds all the anchors of the container that scrolls the DOM to their corresponding elements.
The element that scrolls the DOM can be retrieved by using the [`getPageScroller`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#getPageScrollerFun) method.
Since the default parameter of [`setYStepLengthCalculator`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#setYStepLengthCalculatorFun) is the [`_pageScroller`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/VariablesAbout.md#_pageScroller) variable you don't need to specify the container parameter.

For instance:
```javascript
//Full explicit version
uss.hrefSetup(. . .);
uss.setYStepLengthCalculator(myCalculator, uss.getPageScroller(. . .));

//Simplified version
uss.hrefSetup(. . .);
uss.setYStepLengthCalculator(myCalculator);
```

If you use a custom container to scroll the DOM (perhaps all your elements are inside an element that scrolls them), you can also set the [`_pageScroller`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/VariablesAbout.md#_pageScroller) variable by using the [`setPageScroller`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#setPageScrollerFun) function.

For instance:
```javascript
uss.setPageScroller(myContainer);
uss.hrefSetup(. . .);
uss.setYStepLengthCalculator(myCalculator);
```

Hope it's clearer now :)

**Comment by danfmn** [comment]
Thank you, I will give this a shot today.

**Comment by danfmn** [comment]
I tried using your simplified version and it appears it does not work unless `uss.getPageScroller()` is passed.
```js
uss.hrefSetup(
  true,
  true,
  () => {
    isScrollingAnim = true;
  },
  () => {
    isScrollingAnim = false;
  }
);
uss.setYStepLengthCalculator(EASE_IN_CIRC(50));
```

![image](https://user-images.githubusercontent.com/21001224/192905048-c02d6d36-6795-4e25-a3fb-05efd66251c7.png)

This works:
```js
uss.hrefSetup(
  true,
  true,
  () => {
    isScrollingAnim = true;
  },
  () => {
    isScrollingAnim = false;
  }
);
uss.setYStepLengthCalculator(EASE_IN_CIRC(50), uss.getPageScroller());

```

**Comment by CristianDavideConte** [comment]
It appears that your [`_pageScroller`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/VariablesAbout.md#_pageScroller) variable is `null` at the time of the [`setYStepLengthCalculator`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#setYStepLengthCalculatorFun) invocation which leads me to think you're either using it before the [`load event`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is fired by the browser (which would mean that it's `null` because it hasn't been calculated yet) or you found a bug.

Can you try to wrap the part of your code that uses the USS API functions in an `onload` listener to see if it works?

For instance:
```javascript
window.addEventListener("load", () => {
  //Your code above
  uss.hrefSetup(
   true,
   true,
   () => {
     isScrollingAnim = true;
   },
   () => {
     isScrollingAnim = false;
   }
  );
  uss.setYStepLengthCalculator(EASE_IN_CIRC(50));
});
```

**Comment by danfmn** [comment]
Wrapping the code in the load listener fixed the issue.
Thank you very much.
