### ISSUE TITLE
React.js/Next.js - hrefSetup stops anchor tags' click event propagation

### ISSUE THREAD

**Issue by danfmn** [CristianDavideConte/universalSmoothScroll#11]
**Describe the bug**
`uss.hrefSetup` prevents `a` element onClicks from firing.

**To Reproduce**
1. Call `uss.hrefSetup()`
2. Add an anchor tag with an onClick method. 
```js
<a
  onClick={() => {console.log("running")}}
  className="hover:text-[#F40F00]"
  href="#start"
>
  Home
</a>
```
3. The passed onClick method will not run.

**Expected behavior**
The onClick method should run and the console should log "running"

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 105.0.5195.127 (Official Build) (64-bit)

**Additional context**
The onClick method will run if `uss.hrefSetup()` is not called.

**Comment by CristianDavideConte** [comment]
Hello, 
I don't quite understand what you're trying to do here.
In order to reproduce this behavior you said that you first call [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) and then add an anchor tag to the DOM: is this a dynamically inserted `<a>` tag? Or it's already there when the [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) function is invoked?

In the first case, the [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) function doesn't see the added `<a>` tag (whenever it's called, it looks up all the [`document.links`](https://developer.mozilla.org/en-US/docs/Web/API/Document/links?retiredLocale=en) available at that time but it doesn't know anything about the ones that haven't been added to the DOM yet) so it can't do anything about them.
Since there's a missing curly bracket in your example, can that be the error source?

In the second case, it should not happen, and may be a bug.
Below you should find the javascript equivalent of the situation you described, can you please check if it works:
```javascript
<html>
 <head>
  <style>
   div {
     height: 100vh;
     width: 100vw;
   }
   a {
     position: fixed;
     z-index: 1;
     height: 100px;
     width: 100px;
     bottom: 100px;
     right: 0px;
     background: black;
     display: grid;
     justify-content: center;
     align-items: center;
     color: white;
   }
   #start {
    background: red;
   }
   #end {
    background: blue;
   }
  </style>

  <script src = "https://cdn.jsdelivr.net/npm/universalsmoothscroll@latest/universalsmoothscroll-min.js"></script>
  <script>
   const log = () => console.log("running");
   window.addEventListener("load", () => {
    uss.hrefSetup(true, true, () => console.log("start"), () => console.log("end"));
   })
  </script>
 </head>
 
 <body>
  <a href = "#start" onclick="log()">TOP</a>
  <div id = "start"></div>
  <div id = "end"></div>
 </body>
</html>
```

When clicking the `TOP` button in the bottom-right corner these are the expected outputs:
```javascript
//Option A
running
start
end

//Option B
start
running
end
```

Is either of these options what you see in the browser console?

**Comment by danfmn** [comment]
My apologies. I was not very clear in my original message. 

I have fixed the curly bracket in the message, however that is not the cause, for it existed in the code I had originally wrote. I do believe hrefSetup is finding the anchor tags, for when I click on an anchor tag the smooth scrolling does work. The only functionality that is not working is the onClick method. When I do not call hrefSetup, the onClick method works.

For more context this occurs in my Next.js/React.js application. I will provide a code sandbox and see if I can recreate the issue there when I have the time. For now here's a bit more context on how my application is running:

App.js:
```js
import "../styles/globals.scss";
import { useEffect } from "react";
import "../utils/universalsmoothscroll-min";
import { EASE_IN_CIRC } from "../utils/universalsmoothscroll-ease-functions-min";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    let isScrollingAnim = false;
    const setupUSS = () => {
      uss.hrefSetup(
        true,
        true,
        () => {
          isScrollingAnim = true;
        },
        () => {
          isScrollingAnim = false;
        }
      );
      uss.setYStepLengthCalculator(EASE_IN_CIRC(50), uss.getPageScroller());
    };
    const onScroll = (e) => {
      if (isScrollingAnim) {
        uss.stopScrollingAll();
      }
    };
    window.addEventListener("load", setupUSS);
    window.addEventListener("wheel", onScroll);
    window.addEventListener("touchmove", onScroll);

    return () => {
      window.removeEventListener("load", setupUSS);
      window.removeEventListener("wheel", onScroll);
      window.removeEventListener("touchmove", onScroll);
    };
  }, []);
  return <Component {...pageProps} />;
}

export default MyApp;
```

Rendered Child:
```js
<a
  onClick={() => {console.log("running")}}
  className="hover:text-[#F40F00]"
  href="#start"
>
  Home
</a>
```

**Comment by CristianDavideConte** [comment]
Thank you for clarifing the issue you have.

**Comment by CristianDavideConte** [comment]
Thank you for clarifing the issue, I've actually managed to isolate and reproduce it.

Unfortunately this doesn't seem to be a USS API specific bug but just a Next.js behavior.
Apparently Next.js components don't like it when you call [`event.stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) inside a javascript listener and, if you do so, the `onClick` JSX inline listener will not work.
The code below shows how to trigger this behavior without even importing the API:
```javascript
import { useEffect } from "react";

function MyApp() {
  useEffect(() => {
    document.getElementById("test").addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      console.log("running for real"); //Works fine
    });
  }, []);
  
  return(
    <a
      onClick={() => {console.log("running")}} //Doesn't work
      className="hover:text-[#F40F00]"
      href="#test"
      id="test"
    >
      Home
    </a>
  );
}

export default MyApp;
```

This is exactly what happens inside the [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) function since without it you will need to manually stop the propagation of the click events for each anchor which will defeat the purpose of this high level function (writing as little code as possible to enable anchor-smooth-scrolling).

Since you're already using the [`init parameter`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetup) of the [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) function,  the easiest fix for you would be to move your `onClick` listener inside that function instead of using the JSX version ([`this`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FAQ.md#q-what-is-the-hrefsetups-init-parameter-) may be helpful).

If you need more help or have any other suggestion I'll be glad to listen.

**Comment by danfmn** [comment]
Would you have any other suggestions other than putting my `onClick` method inside the `init parameter`?

The reason I ask is because the init parameter is defined at the top level of my application and I need access to methods/data that are available in much lower levels. In addition to that the components themselves will no longer become reuseable for they will have a dependency on the top level component.

Perhaps we could pass in another argument into `hrefSetup` that will prevent stopping of the propagation. I can't think of a cleaner solution, but in this case I would not mind manually calling `stopPropagation` if it meant I could maintain the `onClick`.

Perhaps I interpreted your proposed solution incorrectly. Let me know what you think.
Thanks for all the help so far.

**Comment by CristianDavideConte** [comment]
Thank you for proposing a solution.
To be honest I don't really like the idea of adding another parameter to [`hrefSetup`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetupFun) just for this since it would be only usefull to users who use a React framework and that this behavior may be changed in the future by React's devs.

I do recognize that this is indeed an issue though and I was thinking that perhaps the [`init parameter`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetup) could be the solution here.
The idea was to not call [`stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) by default but to pass the [`init parameter`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetup) the `click event` as the 3<sup>rd</sup> parameter (the 1<sup>st</sup> being the anchor clicked and the 2<sup>nd</sup> being the element to reach).
If not passed, the default value for the [`init parameter`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/master/docs/FunctionsAbout.md#hrefSetup) would just be a function that calls [`stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation).

This way users who were not interested in handling the `click event` themselves don't have to make any change to their codebase, whilst users who wanted to implement custom click-based behaviors should have full control over the `click event`.  

For instance:
```javascript
//This would behave like the current version
uss.hrefSetup(true, false); //Default prevented, propagation stopped

//This would allow JSX onClick listeners to work
uss.hrefSetup(
  true, 
  false, 
  (anchor, elToReach, event) => { /*Custom code*/ } //Default prevented but the propagation is not stopped!
)
```
But since the [`version 6.1`](https://github.com/users/CristianDavideConte/projects/1) is still a work in progress and this is a breaking change, it may take some time to be available.

For now the quickest and cleanest fix I can think of would be to use the [`mousedown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) or the [`pointerdown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) events since those work fine.

For example:
 ```javascript
import { useEffect } from "react";

function MyApp() {
  useEffect(() => {
    document.getElementById("test").addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      console.log("running too");  //This works
    });
  }, []);

  return(
    <a onPointerDown={() => {console.log("running")}} //This works too
      className="hover:text-[#F40F00]"
      href="#test"
      id="test"
    >
      Home
    </a>
  );
}

export default MyApp;
```

 What do you think?

**Comment by CristianDavideConte** [comment]
The issue has been fixed according to what I had anticipated in the comment above. 
The new documentation can be found in the [`beta branch`](https://github.com/CristianDavideConte/universalSmoothScroll/blob/beta/docs/FunctionsAbout.md#hrefSetup) and [`USS 6.1.0`](https://github.com/users/CristianDavideConte/projects/1) will contain this fix.
