### ISSUE TITLE
Next.js (typescript) - How to import the USS API  

### ISSUE THREAD

**Issue by shinichimg** [CristianDavideConte/universalSmoothScroll#2]
Currently, I have added <script /> tag in the Document file.
Although ESLINT comments "USS is not declared"  everything is still working now on LOCAL, 
but my site is crashed on PRODUCT
Can you explain this bug?

**Comment by CristianDavideConte** [comment]
Hi, 
none of these is actually a USS API specific bug, but you seems to have two different problems here, so I'll try to give two hopefully useful answers.

### 1)  _ESLINT comments "USS is not declared"_
As the mentioned in the ESLint documentation "<strong>_Any reference to an undeclared variable causes a warning unless the variable is explicitly mentioned in a /* global ...*/_</strong> ", so you have to mark the uss variable as "global" if you want this warning to disappear. 
For istance, inside the `universalsmoothscroll-min.js` file you downloaded, you can try to add `/*global uss*/` before any other line of code.
This might be helpful: https://eslint.org/docs/rules/no-undef#rule-details.

### 2) _I have added <script /> [...] but my site crashes_
To me, this sounds like a path-finding problem.
Your Next.js project should have a `public` folder inside which you can put the `universalsmoothscroll-min.js` file.
The path to the API file should just be  `./universalsmoothscroll-min.js` whereas the `./` indicates the `public` folder.
Because the uss variable is already declared inside this file we just need to import it.
In order to do this we can use Next.js's `<Script>` tag and write some API code inside it.
For example:
```javascript
//index.js file (or index.tsx)
import Script from "next/script"

export default function Home() { //Or any other function/component
  return (
    <>
     ... //Divs, Head, etc.
     <Script src="./universalsmoothscroll-min.js" //We import the script
      onLoad={() => { //We execute some API code after the document is fully loaded
        /* 
         * Just as an example, 
         * we enable smooth scroll on the page
         */
        uss.setYStepLengthCalculator(r => {return r / 20 + 1;});
        window.addEventListener("wheel", (e) => {
          e.preventDefault();
          e.stopPropagation();
          uss.scrollYBy(e.deltaY, window, null, false);
        }, {passive:false});
      }}
    /> 
    ... //other components
  </>
  )
}
```
The project structure of the example above is:
```javascript
myapp/
  .next
  node_modules
  pages/
    api/
    index.js
  public/
    favicon.ico
    vercel.svg
    universalsmoothscroll-min.js
  styles/
  ...
```
I wouldn't worry too much about the _typescript_ part of the second problem because any valid javascript code should also be a valid typescript code.
You may find this helpful: https://stackoverflow.com/questions/55165852/next-js-implement-external-js-with-script.

If the problems persist, please share more details about the project's structure and the errors you get so that a better and more specific solution can be found.

**Comment by CristianDavideConte** [comment]
Since 2 weeks has passed without receiving any feedback, I'm closing this issue hoping the proposed solutions were useful and all the problems have been solved.
